name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd apps/web
          npm ci
          cd ../mobile
          npm ci
          cd ../../backend
          npm ci

      - name: Run tests
        run: |
          cd apps/web
          npm test
          cd ../mobile
          npm test
          cd ../../backend
          npm test

      - name: Build web application
        run: |
          cd apps/web
          npm run build

      - name: Build mobile application
        run: |
          cd apps/mobile
          npm run build

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          echo "Deploying to production..."